# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ModPackager
    - name: Build
      run: dotnet build ModPackager --no-restore
    - name: Test
      run: dotnet test ModPackager --no-build --verbosity normal
    - name: IDK
      uses: actions/upload-artifact@v2
      with:
        name: MOD-WINDOWS${{ matrix.os }}-isBundled-${{ matrix.bundled }}
        path: D:\a\GML-Mod-Loader\GML-Mod-Loader\ModPackager\bin\Debug\net7.0\
    - name: ProofOfConcept
      run: dotnet restore ProofOfConcept
    - name: Building ProofOfConcept
      run: dotnet build ProofOfConcept --no-restore
    - name: testing ProofOfConcept
      run: dotnet test ProofOfConcept --no-build --verbosity normal
    - name: uploading it to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: COM-WINDOWS${{ matrix.os }}-isBundled-${{ matrix.bundled }}
        path: D:\a\GML-Mod-Loader\GML-Mod-Loader\ProofOfConcept\bin\Debug\net7.0\
